export const challengeLabData = {
  challenges: [
    {
      id: "challenge-1",
      title: "Develop a Water Quality Monitoring App for Rural Communities",
      organization: "Clean Water Initiative",
      description:
        "Create a mobile application that allows rural communities to test, record, and report water quality data to local authorities and NGOs.",
      category: "environment",
      difficulty: "Intermediate",
      location: "Remote",
      teamSize: "3-5 members",
      duration: "6 weeks",
      impactPoints: 450,
      impactAreas: ["sdg6", "sdg3"],
    },
    {
      id: "challenge-2",
      title: "Design Educational Materials for Underserved Schools",
      organization: "Education For All",
      description:
        "Develop engaging, culturally relevant educational materials for mathematics and science subjects for schools with limited resources.",
      category: "education",
      difficulty: "Beginner",
      location: "Remote",
      teamSize: "2-4 members",
      duration: "4 weeks",
      impactPoints: 300,
      impactAreas: ["sdg4"],
    },
    {
      id: "challenge-3",
      title: "Build a Telemedicine Platform for Rural Health Clinics",
      organization: "Global Health Access",
      description:
        "Develop a low-bandwidth telemedicine solution that connects rural health clinics with urban medical specialists for consultations.",
      category: "health",
      difficulty: "Advanced",
      location: "Remote",
      teamSize: "4-6 members",
      duration: "8 weeks",
      impactPoints: 600,
      impactAreas: ["sdg3"],
    },
    {
      id: "challenge-4",
      title: "Create a Microfinance Management System for Women Entrepreneurs",
      organization: "Women's Economic Empowerment Fund",
      description:
        "Build a simple, user-friendly system to help women entrepreneurs in developing countries manage microloans, savings, and business planning.",
      category: "technology",
      difficulty: "Intermediate",
      location: "Remote",
      teamSize: "3-4 members",
      duration: "6 weeks",
      impactPoints: 400,
      impactAreas: ["sdg1", "sdg5"],
    },
    {
      id: "challenge-5",
      title: "Develop a Food Waste Reduction App for Local Restaurants",
      organization: "Sustainable City Network",
      description:
        "Create an application that helps local restaurants track, reduce, and repurpose food waste, connecting them with food banks and composting services.",
      category: "environment",
      difficulty: "Beginner",
      location: "Local",
      teamSize: "2-3 members",
      duration: "4 weeks",
      impactPoints: 250,
      impactAreas: ["sdg12", "sdg11"],
    },
    {
      id: "challenge-6",
      title: "Design an Accessible Learning Platform for Children with Disabilities",
      organization: "Inclusive Education Alliance",
      description:
        "Create an accessible digital learning platform with adaptive features for children with various disabilities to ensure equal access to education.",
      category: "education",
      difficulty: "Advanced",
      location: "Remote",
      teamSize: "4-5 members",
      duration: "10 weeks",
      impactPoints: 550,
      impactAreas: ["sdg4", "sdg10"],
    },
    {
      id: "challenge-7",
      title: "Build a Community Emergency Response System",
      organization: "Disaster Resilience Network",
      description:
        "Develop a mobile and web-based system that helps communities coordinate emergency responses during natural disasters or crises.",
      category: "community",
      difficulty: "Intermediate",
      location: "Remote",
      teamSize: "3-5 members",
      duration: "7 weeks",
      impactPoints: 500,
      impactAreas: ["sdg11", "sdg13"],
    },
    {
      id: "challenge-8",
      title: "Create a Peer Support Platform for Mental Health",
      organization: "Mind Wellness Foundation",
      description:
        "Design a secure, anonymous platform where individuals can connect with peers for mental health support, guided by professional moderators.",
      category: "health",
      difficulty: "Intermediate",
      location: "Remote",
      teamSize: "3-4 members",
      duration: "6 weeks",
      impactPoints: 400,
      impactAreas: ["sdg3"],
    },
    {
      id: "challenge-9",
      title: "Develop a Solar Energy Calculator for Low-Income Households",
      organization: "Renewable Energy Access",
      description:
        "Build a tool that helps low-income households calculate potential savings and benefits from switching to solar energy, including available subsidies.",
      category: "environment",
      difficulty: "Beginner",
      location: "Remote",
      teamSize: "2-3 members",
      duration: "5 weeks",
      impactPoints: 350,
      impactAreas: ["sdg7", "sdg1"],
    },
  ],

  alternativeActivities: [
    {
      title: "Mentor Coding Bootcamp Students",
      organization: "Tech For All",
      description:
        "Provide mentorship to students from underrepresented backgrounds learning to code through weekly online sessions.",
      category: "Education",
      timeCommitment: "2-4 hours/week",
      frequency: "Weekly for 3 months",
      skillsGained: ["Leadership", "Communication", "Teaching"],
      impactPoints: 300,
    },
    {
      title: "Translate Educational Content",
      organization: "Global Learning Initiative",
      description:
        "Translate educational materials into different languages to make them accessible to non-English speaking communities.",
      category: "Education",
      timeCommitment: "Flexible",
      frequency: "Self-paced",
      skillsGained: ["Language Skills", "Cultural Awareness", "Content Creation"],
      impactPoints: 200,
    },
    {
      title: "Virtual Volunteering with Local NGO",
      organization: "Community Support Network",
      description:
        "Help local non-profits with their digital needs, from website updates to social media management and digital marketing.",
      category: "Community",
      timeCommitment: "3-5 hours/week",
      frequency: "Ongoing",
      skillsGained: ["Digital Marketing", "Content Creation", "Project Management"],
      impactPoints: 250,
    },
    {
      title: "Participate in Citizen Science Projects",
      organization: "Global Science Collaborative",
      description:
        "Contribute to scientific research by collecting and analyzing data for environmental monitoring, wildlife tracking, or astronomy projects.",
      category: "Environment",
      timeCommitment: "1-2 hours/week",
      frequency: "Flexible",
      skillsGained: ["Data Collection", "Analysis", "Scientific Method"],
      impactPoints: 150,
    },
    {
      title: "Tech Support for Seniors",
      organization: "Digital Inclusion Network",
      description:
        "Provide remote technical support and digital literacy training to seniors, helping them stay connected in an increasingly digital world.",
      category: "Community",
      timeCommitment: "2-3 hours/week",
      frequency: "Weekly",
      skillsGained: ["Communication", "Patience", "Technical Support"],
      impactPoints: 200,
    },
    {
      title: "Open Source Contribution to Humanitarian Projects",
      organization: "Code for Good",
      description:
        "Contribute to open-source software projects that address humanitarian challenges and support non-profit organizations.",
      category: "Technology",
      timeCommitment: "Flexible",
      frequency: "Self-paced",
      skillsGained: ["Coding", "Collaboration", "Problem-solving"],
      impactPoints: 350,
    },
  ],
}
